---
# 1. Below playbook performs rundeck server configuration on remote machines
# 2. No manual changes are required in this playbook
# 3. all variables in this playbook reffers to /etc/ansible/vars/main.yml - this playbook does below tasks
# 4. copy rundeck 2.5.2 on remote machine and install rundeck 
# 5. copy vspherejars.tar.gz on remote machine and unzip it under /usr/local
# 6. copy mysql connector on remote machine on path /var/lib/rundeck/exp/webapp/WEB-INF/lib/ for rundeck - mysql
# 7. modify /etc/rundeck/rundeck-config.properties, /etc/rundeck/framework.properties,/etc/rundeck/log4j.properties on remote server
# 8. mount /mnt/ of MysqlJBPMRundeck_Master_BackEnd_RealIP for central rundeck logging
# 9. download git repo stash.gcv-cloud.com/scm/nlb/nfv_rundeck_jobs.git
# 10. create GCV5 Project and load rundeck jobs
# 11. start rundeck
# 12. also please do not change the sequence of below configuration

  - name: install xmlstarlet=1.5, coreutils=8.21, openjdk-7-jre,openjdk-7-jdk, nfs-common=1:1.2.8,mysql-client=5.5.46 packages required for rundeck server configuration
    apt: pkg={{ item }} state=installed
    with_items:
    - xmlstarlet=1.5.0-1
    - coreutils=8.21-1ubuntu5.1
    - openjdk-7-jre
    - openjdk-7-jdk
    - nfs-common=1:1.2.8-6ubuntu1.2
    - mysql-client=5.5.46-0ubuntu0.14.04.2

  - name: copy rundeck-2.5.2-1-GA.deb on remote rundeck server on path /home/{{ ansible_ssh_user }}
    copy: src="rundeck-2.5.2-1-GA.deb" dest="/home/{{ ansible_ssh_user }}/"

  - name: copy vspherejars.tar.gz archieve on /usr/local path of rundeck servers
    copy: src="vspherejars.tar.gz" dest="/usr/local/" owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}

  - name: extract vspherejars.tar.gz archieve on /usr/local path of rundeck server
    command: chdir=/usr/local tar xvf vspherejars.tar.gz -C /usr/local creates=/usr/local/vspherejars

  - name: Install rundeck-2.5.2-1-GA.deb package
    apt: deb="/home/{{ ansible_ssh_user }}/rundeck-2.5.2-1-GA.deb"

  - name: modify /etc/rundeck/rundeck-config.properties using template
    template: src=rundeck-config.properties.j2 dest=/etc/rundeck/rundeck-config.properties backup=yes force=yes

  - name: modify /etc/rundeck/framework.properties using template 
    template: src=framework.properties.j2 dest=/etc/rundeck/framework.properties backup=yes

  - name: modify /etc/rundeck/log4j.properties using template
    template: src=log4j.properties.j2 dest=/etc/rundeck/log4j.properties backup=yes

  - name: copy /etc/rundeck/tokens.properties.j2
    template: src=tokens.properties.j2 dest=/etc/rundeck/tokens.properties

  - name: Copy mysql connector
    copy: src="mysql-connector-java-5.1.36-bin.jar" dest="/var/lib/rundeck/exp/webapp/WEB-INF/lib/" owner=rundeck group=rundeck

  - name: Ensure /var/lib/rundeck/exp/webapp/WEB-INF/lib/ have rundeck permissions
    command: chown -R rundeck:rundeck /var/lib/rundeck/exp/webapp/WEB-INF/lib/  

  - name: mount NFS share for central rundeck logging
    mount: name=/mnt/ src={{ mysql_jbpm_rundeck01_eth1 }}:/mnt fstype=nfs state=mounted

  - name: Ensure  /etc/rundeck have rundeck permissions
    file: path=/etc/rundeck owner=rundeck group=rundeck state=directory recurse=yes

  - name: Ensure  /var/log/rundeck  have rundeck permissions
    file: path=/var/log/rundeck owner=rundeck group=rundeck state=directory recurse=yes

  - name: Ensure /var/lib/rundeck have rundeck permissions
    file: path=/var/lib/rundeck owner=rundeck group=rundeck state=directory recurse=yes

  - name: Ensure /mnt/log  have rundeck permissions
    file: path=/mnt/log owner=rundeck group=rundeck state=directory recurse=yes
    when: inventory_hostname == rundeck01_eth0

  - name: restart rundeck
    service: name=rundeckd state=restarted enabled=yes

  - name: git clone repo
    sudo: no
    command: chdir=/home/{{ ansible_ssh_user }} git clone https://{{ stash_user }}:{{ stash_password }}@stash.gcv-cloud.com/scm/nlb/nfv_rundeck_jobs.git
    when: inventory_hostname == "{{ rundeck01_eth0 }}"

  - name: Just Pause 
    pause: minutes=2

  - name: crete GCV5 project
    command: sudo -S rd-project -a create -p gcv5

  - name: load rundeck jobs for gcv5 project
    command: rd-jobs load -f /home/{{ ansible_ssh_user }}/nfv_rundeck_jobs/gcv/nfv_jobs.xml -p gcv5
    when: inventory_hostname == "{{ rundeck01_eth0 }}"
